version: '3'

services:
  pokaplayer:
    build: .
    ports:
      - "3000"
    networks:
      - pokaplayer
    depends_on:
      - neteaseapi2
      - mongodb
    
  neteaseapi2:
    build: 
      context: .
      dockerfile: NeteaseAPI2_Dockerfile
    networks:
      - pokaplayer
      
  mongodb:
    image: mongo:latest
    command: --smallfiles
    networks:
      - pokaplayer

networks:
  - pokaplayer